curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/cross-domain.ttl\" ]}" > cross-domain-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriCommon.ttl\" ]}" > agriCommon-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriFeature.ttl\" ]}" > agriFeature-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriCrop.ttl\" ]}" > agriCrop-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriIntervention.ttl\" ]}" > agriIntervention-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriAlert.ttl\" ]}" > agriAlert-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriProduct.ttl\" ]}" > agriProduct-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriProperty.ttl\" ]}" > agriProperty-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriSystem.ttl\" ]}" > agriSystem-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriPest.ttl\" ]}" > agriPest-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/farmAnimal.ttl\" ]}" > farmAnimal-SHACL.ttl
curl -v -X POST "https://astrea.linkeddata.es/api/shacl/url" -H "accept: text/rdf+turtle" -H "Content-Type: application/json" -d "{ \"ontologies\": [ \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/cross-domain.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriCommon.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriFeature.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriCrop.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriIntervention.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriAlert.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriProduct.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriProperty.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriSystem.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/agriPest.ttl\", \"https://raw.githubusercontent.com/rapw3k/DEMETER/master/models/farmAnimal.ttl\" ]}" > demeterAgriProfile-SHACL.ttl